class Issue:
    issue_id = 'Issue ID'
    ignored = 'Ignored'
    status = 'Status'
    project_id = 'Project ID'
    library = 'Library'
    version_in_use = 'Version in use'
    library_release_date = 'Library release date'
    package_manager = 'Package manager'
    coordinate1 = 'Coordinate 1'
    coordinate2 = 'Coordinate 2'
    latest_version = 'Latest version'
    latest_release_data = 'Latest release date'
    project = 'Project'
    branch = 'Branch'
    tag = 'Tag'
    issue_opened_scan_id = 'Issue opened: Scan ID'
    issue_opened_scan_date = 'Issue opened: Scan date'
    issue_fixed_scan_id = 'Issue fixed: Scan ID'
    issue_fixed_scan_date = 'Issue fixed: Scan date'
    dependency = 'Dependency (Transitive or Direct'
    scan = 'Scan'
    scan_date = 'Scan date'
    vulnerability_id = 'Vulnerability ID'
    title = 'Title'
    cvss_score = 'CVSS score'
    severity = 'Severity'
    cve = 'CVE'
    public_disclosure = 'Public or Veracode Customer Access'
    disclosure_date = 'Disclosure date'
    has_vulnerable_methods = 'Has vulnerable methods'
    number_of_vulnerable_methods = 'Number of vulnerable methods'
    open = 'Open'
    resolved = 'Resolved'


class Severity:
    high = "High"
    medium = "Medium"
    low = "Low"
